# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hAZtHWrDKiTQvy1RvGb_ymdvR9SYqXyx
"""

pip install -U langchain-community

!pip install langchain pypdf chromadb sentence_transformers huggingface_hub

from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain.llms import HuggingFaceHub

import os
file_name = ("/content/BRIEFLY_DEFINE_ALL_THE_TERMS.docx.pdf")  # Replace with your PDF file name
file_path = os.path.join("/content/", file_name)

from langchain.document_loaders import PyPDFLoader

loader = PyPDFLoader(file_path)
documents = loader.load()

from langchain.text_splitter import RecursiveCharacterTextSplitter

# Initialize the text splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, chunk_overlap=200
)  # Adjust chunk_size and chunk_overlap as needed

texts = text_splitter.split_documents(documents)

# ... rest of your code ...
# Create embeddings and store them in a vector database
embeddings = SentenceTransformerEmbeddings(model_name="all-mpnet-base-v2")
db = Chroma.from_documents(texts, embeddings)

# Create a retrieval QA chain

# Print the number of documents in the database
print(f"Number of documents in the database: {len(db)}")

   # If 0, your database is empty and needs to be populated.
   # If > 0, check the documents for relevance to your query.

!pip install pyngrok

import streamlit as st

st.title("My Chatbot")  # Display a title
st.write("Welcome to the chatbot!")  # Display a text message

user_input = st.text_input("Enter your message:")  # Get user input

if user_input:
  response = qa_chain({"query": user_input}) # Assuming you have a qa_chain defined elsewhere
  st.write("Chatbot:", response['result'])  # Display the chatbot's response

!streamlit run /content/your_script.py & npx localtunnel --port 8501